# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf90f4b0373c85457811ad9db6579474f0ea409e455decce4cd72d79fb7c66932f037afcf6abc3f094965a57283b6872b83dba54c915df6af5b0f8ed29b425bb

test:
  secret_key_base: cd0de01150d69a1fe9fd174ce01914a4ba4c777d30cf42cd1465facc34ebc1cd0510a9ffceb7dc2b52331748d7c4a38b4b32621395daf1b2ffdfaed97864fd4f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
